/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-03 04:08:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>성적관리프로그램</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	*{\n");
      out.write("	magin:0;\n");
      out.write("	padding:0;\n");
      out.write("	}\n");
      out.write("	html,body{\n");
      out.write("	width:100%;\n");
      out.write("	height:100%;\n");
      out.write("	position:absolute;\n");
      out.write("	}\n");
      out.write("	h1{\n");
      out.write("	text-align:center;\n");
      out.write("	}\n");
      out.write("	form{\n");
      out.write("	width:800px;\n");
      out.write("	height:150px;\n");
      out.write("	position:absolute;\n");
      out.write("	top:10%;\n");
      out.write("	marin-top:-75px;\n");
      out.write("	left:50%;\n");
      out.write("	margin-left:-400px;\n");
      out.write("	}\n");
      out.write("	table{\n");
      out.write("	background-color:linen;\n");
      out.write("	width:100%;\n");
      out.write("	height:100%;\n");
      out.write("	border-collapse:collapse;\n");
      out.write("	border:none;\n");
      out.write("	}\n");
      out.write("	tr:nth-child(2) td input{\n");
      out.write("	width:100%;\n");
      out.write("	box-sizing:border-box;\n");
      out.write("	height:40px;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	window.onload = function(){\n");
      out.write("		var frm = document.writeForm;\n");
      out.write("		frm.id.focus();\n");
      out.write("	}\n");
      out.write("	function checkForm(){\n");
      out.write("		var frm = document.writeForm;\n");
      out.write("		if(!frm.id.value){\n");
      out.write("			alert(\"학번을 입력하세요\");\n");
      out.write("			frm.id.focus();\n");
      out.write("		}else if(!frm.name.value){\n");
      out.write("			alert(\"이름을 입력하세요\");\n");
      out.write("			frm.name.focus();\n");
      out.write("		}else if(!frm.korean.value){\n");
      out.write("			alert(\"국어점수를 입력하세요\");\n");
      out.write("			frm.korean.focus();\n");
      out.write("		}else if(!frm.english.value){\n");
      out.write("			alert(\"영어점수를 입력하세요\");\n");
      out.write("			frm.english.focus();\n");
      out.write("		}else if(!frm.math.value){\n");
      out.write("			alert(\"수학점수를 입력하세요\");\n");
      out.write("			frm.math.focus();\n");
      out.write("		}else{\n");
      out.write("			frm.submit();\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<form action=\"scoreWrite.jsp?pg=1\" name=\"writeForm\" method=\"post\" >\n");
      out.write("		<h1>::성적관리 프로그램::</h1>\n");
      out.write("		<table border=\"1\">\n");
      out.write("			<tr>\n");
      out.write("				<th>학번</th>\n");
      out.write("				<th>이름</th>\n");
      out.write("				<th>국어</th>\n");
      out.write("				<th>영어</th>\n");
      out.write("				<th>수학</th>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"id\">\n");
      out.write("				</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"name\">\n");
      out.write("				</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"korean\">\n");
      out.write("				</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"english\">\n");
      out.write("				</td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"text\" name=\"math\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr align=\"center\">\n");
      out.write("				<td colspan=\"5\">\n");
      out.write("					<input type=\"button\" value=\"성적입력\" onclick=\"checkForm()\">\n");
      out.write("					<input type=\"reset\" value=\"다시작성\">\n");
      out.write("					<input type=\"button\" value=\"학생성적목록 바로가기\" onclick=\"location.href='scoreList.jsp?pg=1'\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
